apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  labels:
    app: myapplication
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapplication
  template:
    metadata:
      labels:
        app: myapplication
    spec:
      containers:
      - name: mywebapp
        image: utkarshpratapsingh/mywebapp:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
